package br.com.cams7.sisbarc.aal.ws;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import br.com.cams7.sisbarc.aal.ws.HelloService;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.8 Generated source
 * version: 2.2
 * 
 */
@WebServiceClient(name = HelloServiceImpl.WEBSERVICECLIENT_FULLNAME, targetNamespace = HelloServiceImpl.WEBSERVICECLIENT_TARGETNAMESPACE, wsdlLocation = HelloServiceImpl.WEBSERVICECLIENT_WSDLLOCATION)
public class HelloServiceImpl extends Service {

	public static final String WEBSERVICECLIENT_TARGETNAMESPACE = "http://ws.controller.aal.sisbarc.cams7.com.br/";

	public static final String WEBSERVICECLIENT_NAME = "HelloWSController";

	public static final String WEBSERVICECLIENT_FULLNAME = WEBSERVICECLIENT_NAME
			+ "Service";
	public static final String WEBSERVICECLIENT_WSDLLOCATION = "http://localhost:8080/acende_apaga_leds/sayhello?wsdl";

	private final static URL HELLOSERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static WebServiceException HELLOSERVICEIMPLSERVICE_EXCEPTION;
	private final static QName HELLOSERVICEIMPLSERVICE_QNAME = new QName(
			HelloServiceImpl.WEBSERVICECLIENT_TARGETNAMESPACE,
			HelloServiceImpl.WEBSERVICECLIENT_FULLNAME);

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(WEBSERVICECLIENT_WSDLLOCATION);
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		HELLOSERVICEIMPLSERVICE_WSDL_LOCATION = url;
		HELLOSERVICEIMPLSERVICE_EXCEPTION = e;
	}

	public HelloServiceImpl() {
		super(__getWsdlLocation(), HELLOSERVICEIMPLSERVICE_QNAME);
	}

	public HelloServiceImpl(WebServiceFeature... features) {
		super(__getWsdlLocation(), HELLOSERVICEIMPLSERVICE_QNAME, features);
	}

	public HelloServiceImpl(URL wsdlLocation) {
		super(wsdlLocation, HELLOSERVICEIMPLSERVICE_QNAME);
	}

	public HelloServiceImpl(URL wsdlLocation,
			WebServiceFeature... features) {
		super(wsdlLocation, HELLOSERVICEIMPLSERVICE_QNAME, features);
	}

	public HelloServiceImpl(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public HelloServiceImpl(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns HelloService
	 */
	// HelloServiceImplPort
	@WebEndpoint(name = WEBSERVICECLIENT_NAME + "Port")
	public HelloService getHelloServiceImplPort() {
		return super.getPort(new QName(
				HelloServiceImpl.WEBSERVICECLIENT_TARGETNAMESPACE,
				WEBSERVICECLIENT_NAME + "Port"), HelloService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns HelloService
	 */
	@WebEndpoint(name = WEBSERVICECLIENT_NAME + "Port")
	public HelloService getHelloServiceImplPort(WebServiceFeature... features) {
		return super.getPort(new QName(
				HelloServiceImpl.WEBSERVICECLIENT_TARGETNAMESPACE,
				WEBSERVICECLIENT_NAME + "Port"), HelloService.class, features);
	}

	private static URL __getWsdlLocation() {
		if (HELLOSERVICEIMPLSERVICE_EXCEPTION != null) {
			throw HELLOSERVICEIMPLSERVICE_EXCEPTION;
		}
		return HELLOSERVICEIMPLSERVICE_WSDL_LOCATION;
	}

}
